import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

// Import the Outfit font
const outfit = Outfit({
  subsets: ["latin"], // Specify subsets based on your needs
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Include the weights you need
  variable: "--font-outfit", // Optional: Add a custom variable for the font
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${outfit.variable} antialiased`}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
